# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


# Position Controllers
gimbal_roll_controller:
  type: effort_controllers/JointPositionController
  joint: gimbal_roll_joint
  pid: {p: 100.0, i: 5, d: 7.0}

gimbal_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: gimbal_pitch_joint
  pid: {p: 100.0, i: 5, d: 7.0}

gimbal_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: gimbal_yaw_joint
  pid: {p: 100.0, i: 5, d: 7.0}